### ISSUE TITLE
In the new UI, can the list of runs (by uid) be presented with newest first?

### ISSUE THREAD

**Issue by prjemian** [bluesky/tiled#191]
In the tiled web server UI, the list of runs for a catalog is presented in chronological order, with the newest runs at the end.

As the catalog grows in size, the features of the UI make it tedious to see the newest (likely most interesting) content.  Such as this example (which would take >70 page loads to reach the end of the list):
![pager](https://user-images.githubusercontent.com/2279984/160195890-e8b4a7f7-e367-4b64-a8c1-93d5a6e3641b.png)

The standard media player buttons (`|<`  `<<` `>>`  `>|`) would be helpful but these features might be our of reach for the UI framework.

The ability to sort the list by increasing or decreasing ID (uid) is not useful.

It would be a major advancement to present this list in reverse chronological order by default.  Is it possible?

**Comment by danielballan** [comment]
Sorting works now; click the three dots to the right of the column you want to sort by. Now, for that to solve your problem you need a “time” column to exist. That works too (as shown in the live demo) but we haven’t documented how to do it yet. Will post here later with instructions (it’s easy but I want to double check it).

Reading a little more, I found how to add the pagination buttons in a way that seems reasonable.

**Comment by danielballan** [comment]
As demonstrated at https://tiled-demo.blueskyproject.io/ui/browse/bmm/raw you can add a time column (would be nice to format it prettier...)

At first "Time" column is switched off:

![image](https://user-images.githubusercontent.com/2279598/160698989-569a3814-839e-40b6-ad9f-a73516f5536c.png)

With "Time" column switched on:
 
![image](https://user-images.githubusercontent.com/2279598/160699032-db641fd1-033a-4f2f-b541-52455b96512d.png)

Clicking three dots to the right of the "Time" column and sorting...

![image](https://user-images.githubusercontent.com/2279598/160699389-dc842d44-784a-4640-914b-b465458059e9.png)

## How to do this on your own deployment

The details here are still subject to change without notice but this is how the columns are customized to add bluesky-specific columns:

1. Find `share/tiled` on your system:

```py
>>> import tiled.utils
>>> tiled.utils.get_share_tiled_path()
'/srv/tiled/venv/share/tiled'
```

2. Place this at `share/tiled/ui/config/bluesky.yml`:

```yml
specs:
  - spec: CatalogOfBlueskyRuns
    columns:
      - header: Bluesky Plan
        select_metadata: start.plan_name
        field: plan_name
      - header: Scan ID
        select_metadata: start.scan_id
        field: scan_id
      - header: Time
        select_metadata: start.time
        field: start_time
    default_columns:
      - plan_name
      - scan_id
```

3. Place this at `share/tiled/ui/configuration_management.yml` (replacing the existing file).

```yml
# Relative paths to every UI configuration file.
# To extend the UI (teaching it about additional formats or specs)
# add new configuration. All of these will be loaded.
manifest:
  - config/default.yml
  - config/bluesky.yml
```
