### ISSUE TITLE
/ui/browse route is not accessible from Docker image

### ISSUE THREAD

**Issue by pshafer-als** [bluesky/tiled#338]
When running the `tiled` Docker image on my laptop, the "/ui/browse" route returns 404 Not Found ("detail not found" in the JSON returned). There are no problems accessing the root route, nor any problems using the api routes.

Console output...

```
172.17.0.1:63078 - "GET /?api_key=SECRET HTTP/1.1" 200
172.17.0.1:63080 - "GET /ui/browse?api_key=SECRET HTTP/1.1" 404
172.17.0.1:63082 - "GET /ui/browse/ HTTP/1.1" 404
172.17.0.1:63084 - "GET /ui/browse/?api_key=SECRET HTTP/1.1" 404
172.17.0.1:63086 - "GET /api/node/full// HTTP/1.1" 200
```

At this point I would not rule out user error. Do others experience this same behavior?

**Comment by danielballan** [comment]
I'm curious what @dylanmcreynolds thinks.

**Comment by dylanmcreynolds** [comment]
The docker image already builds the web ui, or at least [attempts to](https://github.com/bluesky/tiled/blob/9d12e1a392ee8ff96bf0c442f1eeaa799dc6da62/docker/Dockerfile#L4).  Perhaps this is failing silently? Or, more likely, not going into the right place for fastapi to be picking it up?

**Comment by pshafer-als** [comment]
Dylan and I tried a few combinations of docker volume mounts and config.yml data directory, some of which were successful.  Here is what worked and what didn't work.  Offhand it seems like the data directory should not be in a subdirectory of '/deploy'?

## Summary

| Successful | Symptomatic |
| --- | --- |
| Config in '/app/config'; data in '/data' | [Tutorial instructions](https://blueskyproject.io/tiled/how-to/docker.html) |
| Config in '/app/config'; data in '/data2' | Config in '/app/config'; data in '/deploy/example_files' |
| Config in '/deploy'; data in '/data2' |  |
| Config in '/deploy'; data in '/data/example_files' |  |

---
---
# Details

## Successful configurations

### Config in '/app/config'; data in '/data'

```
docker run -p 8000:8000 -v "$PWD:/app/config" -v "$PWD/example_files:/data" -e TILED_CONFIG=/app/config/config.yml ghcr.io/bluesky/tiled:main
```

config.yml :

```
# config.yml
trees:
  - path: /
    tree: tiled.adapters.files:DirectoryAdapter.from_directory
    args:
      directory: "/data"
authentication:
  allow_anonymous_access: true
  single_user_api_key: SECRET
```

### Config in '/app/config'; data in '/data2'

Was there something magic about '/data'? **No**

```
docker run -p 8000:8000 -v "$PWD:/app/config" -v "$PWD/example_files:/data2" -e TILED_CONFIG=/app/config/config.yml ghcr.io/bluesky/tiled:main
```

config.yml :

```
# config.yml
trees:
  - path: /
    tree: tiled.adapters.files:DirectoryAdapter.from_directory
    args:
      directory: "/data2"
authentication:
  allow_anonymous_access: true
  single_user_api_key: SECRET
```

### Config in '/deploy'; data in '/data2'

Was there something magic about '/app/config'? **No**

```
docker run -p 8000:8000 -v "$PWD:/deploy" -v "$PWD/example_files:/data2" -e TILED_CONFIG=/deploy/config.yml ghcr.io/bluesky/tiled:main
```

config.yml :

```
# config.yml
trees:
  - path: /
    tree: tiled.adapters.files:DirectoryAdapter.from_directory
    args:
      directory: "/data2"
authentication:
  allow_anonymous_access: true
  single_user_api_key: SECRET
```

### Config in '/deploy'; data in '/data/example_files'

Is it a problem to mount to '/deploy'? **No**, at least not got the config.yml file

```
docker run -p 8000:8000 -v "$PWD:/deploy" -v "$PWD:/data" -e TILED_CONFIG=/deploy/config.yml ghcr.io/bluesky/tiled:main
```

config.yml :

```
# config.yml
trees:
  - path: /
    tree: tiled.adapters.files:DirectoryAdapter.from_directory
    args:
      directory: "/data/example_files"
authentication:
  allow_anonymous_access: true
  single_user_api_key: SECRET
```

---

## Configurations with reported symptoms

'/api' and '/' can be accessed, but '/ui/browse' is not found.

### [Tutorial instructions](https://blueskyproject.io/tiled/how-to/docker.html)

```
docker run --rm -p 8000:8000   --mount type=bind,source="$(pwd)",target=/deploy   --env TILED_CONFIG=/deploy/config.yml ghcr.io/bluesky/tiled:main
```

config.yml :

```
# config.yml
trees:
  - path: /
    tree: tiled.adapters.files:DirectoryAdapter.from_directory
    args:
      directory: "example_files"
      # directory: "/deploy/example_files"  # This behaves the same as the line above
authentication:
  allow_anonymous_access: true
  single_user_api_key: SECRET
```

### Config in '/app/config'; data in '/deploy/example_files'

Was it a problem using the bind mount notation from the tutorial? **No**, get the same symptomatic behavior when data directory '$PWD/example_files' is accessed by container at 'deploy/example_files'.

```
docker run -p 8000:8000 -v "$PWD:/app/config" -v "$PWD:/deploy" -e TILED_CONFIG=/app/config/config.yml ghcr.io/bluesky/tiled:main
```

config.yml :

```
# config.yml
trees:
  - path: /
    tree: tiled.adapters.files:DirectoryAdapter.from_directory
    args:
      directory: "/deploy/example_files"
authentication:
  allow_anonymous_access: true
  single_user_api_key: SECRET
```
