### ISSUE TITLE
Rename config field `path:` to `prefix:`

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled#508]
Rename `path` to `prefix` in this context:

```yaml
trees:
- tree: ...
  prefix: /  # <-- renamed from 'path'
  args:
    ...
```

* It avoid ambiguity with paths in the `args:`, such as the path of files to be served or storage to be written to.
* It exactly matches the usage of the term `prefix` in FastAPI.

I think @pshafer-als suggested something like this, maybe not in exactly this context. Anyway, having looked at this config files a lot recently, I think it's worth a rename. We can run a deprecation cycle so that the old name still works, but issues a warning.
