### ISSUE TITLE
How to serve a directory of msgpack files?

### ISSUE THREAD

**Issue by prjemian** [bluesky/tiled#536]
Is there a configuration example for a file directory of msgpack files?  Such as prepared by databroker-unpack or a temporary databroker catalog?

**Comment by prjemian** [comment]
Ok.  I was hoping to provide some of the catalog I use for CI testing.  Here is my initial config, that failed to recognize the msgpack files:

```yaml
# config.yml

# tiled serve config --public --host 0.0.0.0 config.yml
# http://SERVER.xray.aps.anl.gov:8000/

trees:

  - path: examples
    tree: files
    args:
      directory: /tmp/examples
      key_from_filename: tiled.adapters.files:identity
      mimetypes_by_file_ext:
        .msgpack: application/x-msgpack
```
