### ISSUE TITLE
Support TIFF sequences out of the box.

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled#63]
Currently, the basic usage

```
tiled serve directory ...
```

does not support TIFF sequences. You need a configuration like

```yaml
# config.yml
trees:
  - tree: files
    path: /
    args:
      directory: ...
      subdirectory_handler: tiled.readers.tiff_sequence:subdirectory_handler  # detect directories of TIFF sequences
```

```
tiled serve config config.yml
```

Once we have confidence in `tiled.readers.tiff_sequence:subdirectory_handler`, and perhaps after we have a couple more examples of `subdirectory_handler` under our belt, we should consider configuring a default `subdirectory_handler` that handles TIFF sequences and other multi-file data sources like Zarr and TileDB, out of the box.
