### ISSUE TITLE
Container cannot start (when using local and init_if_not_exists db?) when running with uid/gid set

### ISSUE THREAD

**Issue by DiamondJoseph** [bluesky/tiled#855]
To be able to mount the DLS filesystem at Diamond from the cluster, a pod must be running as non-root, with a uid/gid mapped to a kubernetes user with appropriate permissions on the filesystem to read/write files.

Deploying a known working configuration of tiled into the kubernetes cluster does not work after changing who the pod is running as:

```yaml
podSecurityContext:
  runAsUser: <uid>
  runAsGroup: <gid>
  
securityContext:
  runAsUser: <uid>
  runAsGroup: <gid>
```

[logs-from-tiled-in-tiled-7d7fbccd59-hnfbn.log](https://github.com/user-attachments/files/18506209/logs-from-tiled-in-tiled-7d7fbccd59-hnfbn.log)

I'm assuming it has something to with creating the sqlite database?

This is otherwise using the default Helm configuration:

```yaml
  authentication:
    allow_anonymous_access: false
  trees:
    - path: /
      tree: catalog
      args:
        uri: "sqlite+aiosqlite:////storage/catalog.db"
        writable_storage: "/storage/data"
        init_if_not_exists: true
```
