### ISSUE TITLE
Support writable blob storage

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled#905]
## Overview

Tiled current supports to forms of writable storage:
- SQL database for appendable tabular datasets
- filesystem for everything else (arrays as Zarr, sparse arrays as parquet files, awkward array as buffers on disk)

This issue is to add a third form of writable storage, with an `s3://...` URI, that would you preferred over `filesystem` if present. To start, it could be used by the Zarr Adapter, which I believe supports blob storage natively (maybe via `fsspec`). That is, each chunk is stored as a blob rather than as a file on disk.

## Why Do We Want This?

- We are already beginning to bump into scaling limitations storing data as files on disk, with too many files in one directory. Blob storage lets us scale "wider".
- We envision detectors moving from file-based storage to blob storage in the medium- and long-term, and Tiled should be ready to support that.

## Dev Environment

This is the probably the right way to get a local blob store to develop against. I see a container in there: https://github.com/minio/minio

Before involving Tiled, test that you can write Zarr arrays in there. These docs pages look relevant:
- https://zarr.readthedocs.io/en/v3.0.0/user-guide/storage.html
- https://zarr.readthedocs.io/en/v3.0.0/api/zarr/storage/index.html#zarr.storage.FsspecStore

## Implementation

Extend this `Storage` class, trivially, add a `blob` key:

https://github.com/bluesky/tiled/blob/14c0220cbabc96863f84948bb348482bf7f05022/tiled/structures/data_source.py#L49-L57

I _think_ no changes are needed to the CLI or the config parsing; any `s3://...` URI provided via either entry point should flow through as is.

I _think_ no changes are needed to the [`tiled.catalog.adapter`](https://github.com/bluesky/tiled/blob/main/tiled/catalog/adapter.py) module because `writable_storage` should just flow through.

This will need to be updated to consult whether `writable_storage` has `blob` value set and use that, or fall back to the current behavior using filesystem storage.

From there, we could do the same for some other adapters that support writing.

**Comment by Kezzsim** [comment]
For posterity and due to the fragmented nature of [zarr](https://zarr.readthedocs.io/en/v3.0.0/user-guide/storage.html) and [fsspec](https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.filesystem) documentation, we've prepared an example script here which will let us write data to a bucket in the way that Tiled eventually will. This uses minio to create a local S3 compatible object store which we can write data to. The blob storage server has to be run first via docker compose because it needs a secondary client container to come online and instantiate it:
``` yml
version: "3.2"
services:
  s3:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
    command: server /data --console-address :9001
    restart: unless-stopped

  create-bucket:
    image: minio/mc:latest
    environment:
      MC_HOST_minio: http://${MINIO_ROOT_USER}:${MINIO_ROOT_PASSWORD}@s3:9000
    entrypoint:
      - sh
      - -c
      - |
        until mc ls minio > /dev/null 2>&1; do
          sleep 0.5
        done

        mc mb minio/post-bucket

volumes:
  minio-data:
```

While that service is up you can login to the minio management portal with the username & password `minioadmin` on [localhost port 9001](http://localhost:9001/) to create buckets and run this script to write test data to it (replacing the bucket name with what you created in the UI):

``` python
import zarr
import s3fs
import numpy as np

bucket = "buck"
name = "sample"

s3 = s3fs.S3FileSystem(
    client_kwargs={"endpoint_url": "http://localhost:9000"},
    key="minioadmin",
    secret="minioadmin",
    use_ssl=False,
)
s3store = s3fs.S3Map(root=f'{bucket}/{name}', s3=s3)

data = np.random.random((100, 100))
zarr.save(s3store, data)
```

A key distinction is that this code works with the same version of Zarr that Tiled uses (releases prior to 3.0)
