### ISSUE TITLE
Rework AccessControlPolicy

### ISSUE THREAD

**Issue by danielballan** [bluesky/tiled#951]
_Documenting design conversations with @nmaytan and others._

The current `AccessControlPolicy` enables server admins to define access policies with a Python class that filters results based on `metadata`. We have found that relying on `metadata` to access rules gets messy. We propose to add a new column to the `nodes` table for this purpose, alongside but separate from `metadata`.

We want to retain the current flexibility for different facilities / server admins to implement policies tailored to their requirements. In support of this, the content of this column will be an opaque JSON blob, from Tiled's point of view. It is a dedicated space for the AccessControlPolicy to leave a note to itself, which can be then be incorporated efficiently in queries that filter the nodes that a user can access.

## Example

1. An authenticated user creates a dataset. The AccessControlPolicy will be consulted and provide JSON to be stored with this node, based on the identity of the authenticated user: `{"user": "dallan@bnl.gov"}`.
2. When the users access datasets, any nodes marked up their `user` are included in the results that they can access.
4. The user may, at time of creation or later, apply tags to the dataset. The AccessControlPolicy maintains a notion of which users may apply which tags. When a tag is applied, the JSON stored with the node is updated, such as `{"tags": ["beamline_xyz", "proposal_12345"]}`. Now the identity of the creator is no longer relevant; the node is accessible to any users or groups associated with this tag.

An AccessPolicy will be applied to the server as a whole, not per-tree.

**Comment by danielballan** [comment]
In the example above, the AccessControlPolicy resolves each tag to an access control list, including users and groups and associated scopes for each.

If the AccessControlPolicy were configured with a YAML file, it might look like this:

```yaml
# Define roles, lists of scopes
roles:
  - role: facility_user
    scopes: ["read:data", ...]
  - role: beamline_scientist
    scopes: ["read:data", ...]

# For each tag, list users and/or groups
tags:
  - tag: proposal_12345
    users:
      - user: dallan
        role: ...
      - user: nmaytan
        scopes: ["read:metadata"]  # allowed to hard-code one-off scopes?
  - tag: beamline_xyz
    groups:
      - group: instadmin-xyz
        role: ...
- tag: data_admins
  users:
    - user: msnyder
      role: ...

# Who can add and remove a given tag to a node they have access to?
tag_owners:
  proposal_12345:
    groups:
       - foo
```


```py
class AccessControlPolicy:
    def __init___(self, config: dict):
       self.config = config
       self.acls = compile(config)
 
    def init_node(self, principal, tags=None) -> JSON:
        if not tags:
            return {"user": principal}  # approximately
        else:
            # Check that user has permission to apply each tag in tag_owners config.
            ...
            return {"tags": tags}

    def filter(self, principal: Principal, scopes: Set[Scopes]) -> List[Queries]:
        # Consult ACLs for which sets of tags would confer the necessary scopes
        # to this principal.

        # This would be a query expression, not a string, but you get the idea...
        return "WHERE (access.user == principal) OR (access.tags == ...)"

     def allowed_scopes(principal: Principal, access: JSON) -> Set[Scopes]:
        # Consult ACLs and return a list of the union on all scopes conferred by the access.
```
